apiVersion: apps/v1  
kind: Deployment 
metadata: 
  name: aspnet-mssql
spec: 
  selector: 
    matchLabels: 
      app: aspnet-mssql 
  replicas: 1 
  template:
    metadata: 
      labels: 
        app: aspnet-mssql
    spec: 
      containers: 
      - name: aspnet-mssql 
        image: imagesaks.azurecr.io/aspnet-mssql:latest
        imagePullPolicy: Always
        ports: 
        - containerPort: 80 
--- 

kind: Service 
apiVersion: v1 
metadata: 
  name: aspnet-mssql-service 
spec: 
  selector: 
    app: aspnet-mssql
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80
  type: LoadBalancer 